### ISSUE TITLE
想请教一下语料是从哪里获取的

### ISSUE THREAD

**Issue by guomann** [pakrchen/text-antispam#11]

**Comment by godshen** [comment]
我都是百度自己搜来的野料, 插个眼等大神分享

**Comment by JessYan0913** [comment]
有没有适合垃圾评论的语料库， 找了很久这方面的语料库几乎没有呀

**Comment by codeman008** [comment]
有木有哪位大神分享一下，感谢

**Comment by pakrchen** [comment]
https://github.com/tensorlayer/text-antispam/blob/master/word2vec/data/msglog.tar.gz
