### ISSUE TITLE
貌似效果不是很好

### ISSUE THREAD

**Issue by Tryking** [pakrchen/text-antispam#2]
貌似效果不是很好

**Comment by xjzhou** [comment]
同样的感觉，如果优化的话，最简单有效的是优化语料数据还是训练代码，或者模型？

**Comment by pakrchen** [comment]
效果不好具体是指什么？三个模型运行的结果分别是多少？

**Comment by xjzhou** [comment]
比如我给几个具体的例子。我用的默认 server.py，测试几个效果

![image](https://user-images.githubusercontent.com/1255410/41642665-94719a42-749b-11e8-83a5-1a8bdc42bf30.png)

![image](https://user-images.githubusercontent.com/1255410/41642710-b176ecf0-749b-11e8-826f-df3f189571d7.png)

![image](https://user-images.githubusercontent.com/1255410/41642798-ee0fd55a-749b-11e8-8f9d-a5e290cd96d7.png)

**Comment by pakrchen** [comment]
在text2vec.py和text_features.py中都是把spam标记为0，pass标记为1。你给的结果按照这种标记应该是正确的。

**Comment by pakrchen** [comment]
如果你有具体业务场景的标记数据，添加训练数据是最简单有效的优化方法。

**Comment by xjzhou** [comment]
方便加个微信吗(我的微信见截图)？哈哈想起这个会被antispam掉。我也以为可能0是spam，但是，这个case确是1

![image](https://user-images.githubusercontent.com/1255410/41644458-ab017052-74a0-11e8-9209-156604e9dd85.png)

**Comment by pakrchen** [comment]
训练用的数据集主要是短信，像“加我微信有福利”这类样本一般是在网络评论上容易出现，得加入数据集中重新训练。
训练数据集中的中文短信样本来源：https://github.com/hrwhisper/SpamMessage/tree/master/data
英文短信样本来源：http://www.esp.uem.es/jmgomez/smsspamcorpus/

**Comment by vinayakumarr** [comment]
How to do it character level and this I have to apply for 21 classes. Which are all changes has to be done

**Comment by zhaocaicat** [comment]
> 训练用的数据集主要是短信，像“加我微信有福利”这类样本一般是在网络评论上容易出现，得加入数据集中重新训练。
> 训练数据集中的中文短信样本来源：https://github.com/hrwhisper/SpamMessage/tree/master/data
> 英文短信样本来源：http://www.esp.uem.es/jmgomez/smsspamcorpus/
那如果是这种变体文本的话，需要将这个变体文本作为样本加入进去训练，这样网络才能识别变体的文本吗？
