### ISSUE TITLE
500: Internal Server Error

### ISSUE THREAD

**Issue by zhengxianru** [pakrchen/text-antispam#20]
好像还是跑不通，cnn_classfier和rnn有ValueError无法继续进行，mlp.classfier.py虽然可以正常训练，但是serving_mlp.py之后浏览器无法还是检测
运行http://127.0.0.1/predict?text=加我微信XXXX有福利  还是有错
500: Internal Server Error
不知道是不是我运行操作有问题 十分期望能正常运行检测变体垃圾文本，期待能得到作者回复！

**Comment by TimSYQQX** [comment]
可以用docker logs CONTAINER_NAME查看docker 报错，查看后可以把结果贴在这里。

**Comment by zhengxianru** [comment]
好的，因为我对docker也是不太熟悉没用过，我今天再查看一下报错。还有就是想问能否不使用docker而在本地运行访问呢::&gt;_<::



---Original---

**Comment by TimSYQQX** [comment]
模型的部署也是很重要的技能，还是推荐练习一下docker。本地运行可以用keras load model并 predict。

**Comment by hcolde** [comment]
> 可以用docker logs CONTAINER_NAME查看docker 报错，查看后可以把结果贴在这里。

* **docker logs**
![image](https://user-images.githubusercontent.com/24189814/100951048-b1b0bf00-3548-11eb-91e6-c152697410cc.png)

* **本地模型路径**
![image](https://user-images.githubusercontent.com/24189814/100951103-d3aa4180-3548-11eb-830a-c34cc27a9d46.png)

* **docker运行指令**
docker run -dt -p 8501:8501 -v /Users/colde/Develop/text-antispam/network/saved_models:/models/saved_model -e MODEL_NAME=saved_model --name ttt tensorflow/serving

**Comment by Tr-buaa** [comment]
如果mlp能够成功训练、使用keras的predict预测、并且能够导出模型，即saved_models目录中有文档中所说的结构。那么很可能就是serving部署出了问题。我加载Serving的Docker命令为：
docker run -dt -p 8501:8501 -v D:\text-antispam-master\network\saved_models\mlp:/models/saved_model -e MODEL_NAME=saved_model tensorflow/serving &
注意看看模型保存的路径是否有误，然后运行mlp_serving，输入网址与预测文本即可得到结果

**Comment by hcolde** [comment]
> 如果mlp能够成功训练、使用keras的predict预测、并且能够导出模型，即saved_models目录中有文档中所说的结构。那么很可能就是serving部署出了问题。我加载Serving的Docker命令为：
> docker run -dt -p 8501:8501 -v D:\text-antispam-master\network\saved_models\mlp:/models/saved_model -e MODEL_NAME=saved_model tensorflow/serving &
> 注意看看模型保存的路径是否有误，然后运行mlp_serving，输入网址与预测文本即可得到结果

是的，模型的保存路径不对，感谢指点

**Comment by zhengxianru** [comment]
> 如果mlp能够成功训练、使用keras的predict预测、并且能够导出模型，即saved_models目录中有文档中所说的结构。那么很可能就是serving部署出了问题。我加载Serving的Docker命令为：
> docker run -dt -p 8501:8501 -v D:\text-antispam-master\network\saved_models\mlp:/models/saved_model -e MODEL_NAME=saved_model tensorflow/serving &
> 注意看看模型保存的路径是否有误，然后运行mlp_serving，输入网址与预测文本即可得到结果

好的好的 谢谢 再请问一下有变体文本检测的原始数据嘛，项目里的数据好像是做过预处理之后的？

**Comment by Tr-buaa** [comment]
> > 如果mlp能够成功训练、使用keras的predict预测、并且能够导出模型，即saved_models目录中有文档中所说的结构。那么很可能就是serving部署出了问题。我加载Serving的Docker命令为：
> > docker run -dt -p 8501:8501 -v D:\text-antispam-master\network\saved_models\mlp:/models/saved_model -e MODEL_NAME=saved_model tensorflow/serving &
> > 注意看看模型保存的路径是否有误，然后运行mlp_serving，输入网址与预测文本即可得到结果
> 
> 好的好的 谢谢 再请问一下有变体文本检测的原始数据嘛，项目里的数据好像是做过预处理之后的？

项目里的数据就是做了分词之后的，我也没有原始数据欸
