### ISSUE TITLE
样本库是怎么更新的呢

### ISSUE THREAD

**Issue by qijiaojiao** [pakrchen/text-antispam#3]
请问下，您的样本库是怎么更新的呢？难道把在实际应用中的句子根据最终的分类结果再放回到样本库么？

**Comment by pakrchen** [comment]
如果有新的类型的垃圾信息，需要标注后加入样本库。图6 给了一个样本库更新的方法，https://github.com/pakrchen/text-antispam/tree/master/serving 。
