### ISSUE TITLE
用docker部署好之后，要导出模型，在哪里可以找到tensorflow_model_server呢？

### ISSUE THREAD

**Issue by zhaocaicat** [pakrchen/text-antispam#6]

**Comment by zhaocaicat** [comment]
是我粗心把路径写错了，感谢陈老师的耐心解答，陈老师很nice,Thank you!

**Comment by kulina** [comment]
在docker中执行命令tensorflow_model_server加上参数就可以了，具体的使用可以参考这篇[CSDN](https://blog.csdn.net/u013714645/article/details/81449487?utm_source=blogxgwz3)
