### ISSUE TITLE
No versions of servable default found under base path

### ISSUE THREAD

**Issue by zhaocaicat** [pakrchen/text-antispam#7]
在启动TensorFlow serving的时候，执行了tensorflow_model_server --port=9000 --model_base_path=/home/ubuntu/workspace/GTXiao/text-antispam/network/output/rnn_model/1/variables
其中model_base_path为导出模型的绝对路径，但是出现了2018-12-17 17:42:17.913282: W tensorflow_serving/sources/storage_path/file_syste                                                                         m_storage_path_source.cc:268] No versions of servable default found under base p                                                                            ath /home/ubuntu/workspace/GTXiao/text-antispam/network/output/rnn_model/1/varia                                                                             bles的错误。

**Comment by pakrchen** [comment]
试试tensorflow_model_server --port=9000 --model_base_path=/home/ubuntu/workspace/GTXiao/text-antispam/network/output/rnn_model
