### ISSUE TITLE
接下来需要生成Python可以直接调用的功能库。首先将这三个文件复制到serving/ tensorflow目录下:

### ISSUE THREAD

**Issue by zhaocaicat** [pakrchen/text-antispam#8]
serving底下并没有TensorFlow这个文件夹呢？如果没有，这里需要自己下载一个TensorFlow的源码吗？

**Comment by pakrchen** [comment]
新版本的tensorflow/serving项目下确实没有tensorflow文件夹了，通过选择Branch为r1.0还可以看到有tensorflow文件夹。如果要通过文中的方式生成python可以调用的grpc功能库，最好用r1.0的代码。但是tensorflow serving已经提供http的访问方式了，建议你可以选择tensorflow serving的restful api更加简单。https://www.tensorflow.org/tfx/serving/api_rest

**Comment by pakrchen** [comment]
在写这篇文章的时候，TensorFlow Serving还没有官方的pip包用以供python调用其gRPC API，但是现在已经有了，可以通过以下命令很方便地安装TensorFLow Serving Python客户端代码。通过这种方式安装可以忽略以下生成Python功能库的复杂流程。
